name: globalbarbertool
description: global barber tool

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  ###
  # Dependencies
  ###
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  geolocator: ^10.0.1
  intl: ^0.18.0
  just_audio: ^0.9.35
  location: ^5.0.3
  logger_fork: 1.2.0
  logger_flutter_fork: ^1.3.1
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  url_launcher: ^6.1.14
  go_router: ^10.2.0
  flutter_dotenv: ^5.0.2

  # Freezed
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  # UI
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: 1.1.1
  video_player: ^2.7.2
  google_fonts: ^6.0.0
  easy_localization: ^3.0.3
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0

  # Riverpod
  flutter_riverpod: ^2.4.0

  # Hive
  hive: 2.2.3
  hive_flutter: 1.1.0

  # Firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2

  # Auth
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  json_annotation: ^4.8.1
  country_picker: ^2.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  ###
  # Dev Dependencies
  ###
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  hive_generator: ^2.0.1
  freezed: ^2.4.2

# Trigger code generation
# flutter packages pub run build_runner build --delete-conflicting-outputs

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/movie_list.json
